Update Dl.yml

diff --git a/.github/workflows/Dl.yml b/.github/workflows/Dl.yml
--- a/.github/workflows/Dl.yml
+++ b/.github/workflows/Dl.yml
@@ -64,11 +64,6 @@ jobs:
               echo "$url"
           }
 
-          if [[ -z "${{ github.event.inputs.upl }}" ]]; then
-              echo "No URLs provided, exiting."
-              exit 1
-          fi
-
           urls=$(echo "${{ github.event.inputs.upl }}" | tr ',' '\n')
           for url in $urls; do
               prepared_url=$(prepare_url "$url")
@@ -83,27 +78,17 @@ jobs:
                 --max-connection-per-server=4 \
                 --split=8 \
                 --min-split-size=5M \
-                # --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" \
-                --header="Accept: */*" \
-                --header="Connection: keep-alive" \
                 -d dloa \
                 "$prepared_url" &
 
               pids+=($!)
           done
 
-          if [[ ${#pids[@]} -eq 0 ]]; then
-              echo "No downloads were started."
-              exit 1
-          fi
-
           for pid in "${pids[@]}"; do
               wait $pid
-              exit_code=$?
-              if [ $exit_code -eq 0 ]; then
-                  echo "Download succeeded for PID: $pid"
-              else
-                  echo "Download failed for PID: $pid with exit code $exit_code" >&2
+              if [ $? -ne 0 ]; then
+                  echo "Error: Download failed for PID $pid." >&2
+                  exit 1
               fi
           done
           
