Update Dl.yml

diff --git a/.github/workflows/Dl.yml b/.github/workflows/Dl.yml
--- a/.github/workflows/Dl.yml
+++ b/.github/workflows/Dl.yml
@@ -83,7 +83,7 @@ jobs:
                 --max-connection-per-server=4 \
                 --split=8 \
                 --min-split-size=5M \
-                --referer="https://www.google.com"
+                --referer="https://www.google.com" \
                 --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" \
                 -d dloa \
                 "$prepared_url" &
@@ -98,12 +98,13 @@ jobs:
 
           for pid in "${pids[@]}"; do
               wait $pid
-              if [ $? -eq 0 ]; then
+              exit_code=$?
+              if [ $exit_code -eq 0 ]; then
                   echo "Download succeeded for PID: $pid"
               else
-                  echo "Download failed for PID: $pid" >&2
+                  echo "Download failed for PID: $pid with exit code $exit_code" >&2
               fi
-          done     
+          done
           
       - name: Check files in dloa directory
         run: |
