Update Extract_from_iso_file.yml

diff --git a/.github/workflows/Extract_from_iso_file.yml b/.github/workflows/Extract_from_iso_file.yml
--- a/.github/workflows/Extract_from_iso_file.yml
+++ b/.github/workflows/Extract_from_iso_file.yml
@@ -10,6 +10,10 @@ on:
         required: true
         type: string
         default: '32'
+      extract_exe:
+        description: 'Extract .exe files?'
+        type: boolean
+        default: 'false'
 
 permissions:
   contents: write
@@ -74,11 +78,15 @@ jobs:
           fi
           echo "ISO file found: $ISO_FILE"
 
-          # Создаем директорию для извлеченных файлов
           mkdir -p ${{ github.workspace }}/download/extracted_files
 
-          # Извлекаем только .dll и .ini файлы
-          7z x "$ISO_FILE" -o"${{ github.workspace }}/download/extracted_files" -r -y "*.dll" "*.ini" || { echo "Failed to extract files."; exit 1; }
+          if [ "${{ github.event.inputs.extract_exe }}" == "true" ]; then
+            echo "Extracting .dll, .ini, and .exe files."
+            7z x "$ISO_FILE" -o"${{ github.workspace }}/download/extracted_files" -r -y "*.dll" "*.ini" "*.exe" || { echo "Failed to extract files."; exit 1; }
+          else
+            echo "Extracting only .dll and .ini files."
+            7z x "$ISO_FILE" -o"${{ github.workspace }}/download/extracted_files" -r -y "*.dll" "*.ini" || { echo "Failed to extract files."; exit 1; }
+          fi
 
           echo "Extracted files:"
           find ${{ github.workspace }}/download/extracted_files -type f | while read -r file; do
@@ -91,10 +99,10 @@ jobs:
         run: |
           find ${{ github.workspace }}/download/extracted_files -type f | while read -r file; do
             crc32_value=$(python3 -c "
-          import zlib
-          with open('$file', 'rb') as f:
-              print(f'{zlib.crc32(f.read()):08X}')
-          ")
+              import zlib
+              with open('$file', 'rb') as f:
+                  print(f'{zlib.crc32(f.read()):08X}')
+            ")
             echo "File: $file, CRC32: $crc32_value"
           done
         continue-on-error: true
@@ -110,26 +118,38 @@ jobs:
             exit 1
           fi
 
-          # Перемещаем файлы с нужными расширениями в корень extracted_files
           find "${{ github.workspace }}/download/extracted_files" -type f \( -name "*.dll" -o -name "*.ini" \) -exec mv {} "${{ github.workspace }}/download/extracted_files/" \;
 
-          # Проверка наличия файлов после перемещения
+          if [ "${{ github.event.inputs.extract_exe }}" == "true" ]; then
+            find "${{ github.workspace }}/download/extracted_files" -type f -name "*.exe" -exec mv {} "${{ github.workspace }}/download/extracted_files/" \;
+          fi
+
           DLL_FILES=$(find "${{ github.workspace }}/download/extracted_files" -maxdepth 1 -type f -name "*.dll")
           INI_FILES=$(find "${{ github.workspace }}/download/extracted_files" -maxdepth 1 -type f -name "*.ini")
+          EXE_FILES=$(find "${{ github.workspace }}/download/extracted_files" -maxdepth 1 -type f -name "*.exe")
 
-          if [ -z "$DLL_FILES" ] && [ -z "$INI_FILES" ]; then
-            echo "No .dll or .ini files found."
+          if [ -z "$DLL_FILES" ] && [ -z "$INI_FILES" ] && [ -z "$EXE_FILES" ]; then
+            echo "No .dll, .ini or .exe files found."
             echo "upload_files=false" >> $GITHUB_ENV
           else
-            echo "DLL files found:"
-            echo "$DLL_FILES"
-
-            echo "INI files found:"
-            echo "$INI_FILES"
+            if [ ! -z "$DLL_FILES" ]; then
+              echo "DLL files found:"
+              echo "$DLL_FILES"
+            fi
+            
+            if [ ! -z "$INI_FILES" ]; then
+              echo "INI files found:"
+              echo "$INI_FILES"
+            fi
+            
+            if [ ! -z "$EXE_FILES" ]; then
+              echo "EXE files found:"
+              echo "$EXE_FILES"
+            fi
 
             echo "upload_files=true" >> $GITHUB_ENV
           fi
-
+          
       - name: Upload to GitHub Releases
         if: env.upload_files == 'true'
         uses: softprops/action-gh-release@v2
@@ -138,5 +158,6 @@ jobs:
           files: |
             ${{ github.workspace }}/download/extracted_files/*.dll
             ${{ github.workspace }}/download/extracted_files/*.ini
+            ${{ github.workspace }}/download/extracted_files/*.exe
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
