Update Extract_from_iso_file.yml

diff --git a/.github/workflows/Extract_from_iso_file.yml b/.github/workflows/Extract_from_iso_file.yml
--- a/.github/workflows/Extract_from_iso_file.yml
+++ b/.github/workflows/Extract_from_iso_file.yml
@@ -29,13 +29,13 @@ jobs:
           sudo apt-get install -y aria2 p7zip-full python3
 
       - name: Create Download Directory
-        run: mkdir -p ${{ github.workspace }}/download
+        run: mkdir -p download
 
       - name: Download ISO
         run: |
-          aria2c "${{ github.event.inputs.iso_url }}" -d ${{ github.workspace }}/download || { echo "Download failed"; exit 1; }
+          aria2c "${{ github.event.inputs.iso_url }}" -d download || { echo "Download failed"; exit 1; }
           echo "Downloaded ISO files:"
-          find ${{ github.workspace }}/download -type f | while read -r file; do
+          find download -type f | while read -r file; do
             file_size_human=$(stat -c "%s" "$file")
             file_size_readable=$(stat -c "%s" "$file" | numfmt --to=iec)
             echo "$file $file_size_readable ($file_size_human bytes)"
@@ -43,7 +43,7 @@ jobs:
 
       - name: Verify Downloaded ISO
         run: |
-          for file in ${{ github.workspace }}/download/*; do
+          for file in download/*; do
             crc32_value=$(python3 -c "
           import zlib
           with open('$file', 'rb') as f:
@@ -54,11 +54,11 @@ jobs:
         continue-on-error: true
 
       - name: Create Mount Point
-        run: mkdir -p ${{ github.workspace }}/download/mnt/iso
+        run: mkdir -p download/mnt/iso
 
       - name: View ISO Contents
         run: |
-          ISO_FILE=$(find ${{ github.workspace }}/download -name "*.iso" -type f | head -n 1)
+          ISO_FILE=$(find download -name "*.iso" -type f | head -n 1)
           if [ -z "$ISO_FILE" ]; then
             echo "No ISO file found!"
             exit 1
@@ -70,23 +70,23 @@ jobs:
 
       - name: Extract Specific Files from ISO
         run: |
-          ISO_FILE=$(find ${{ github.workspace }}/download -name "*.iso" -type f | head -n 1)
+          ISO_FILE=$(find download -name "*.iso" -type f | head -n 1)
           if [ -z "$ISO_FILE" ]; then
             echo "No ISO file found!"
             exit 1
           fi
           echo "ISO file found: $ISO_FILE"
 
-          mkdir -p ${{ github.workspace }}/download/extracted_files
+          mkdir -p download/extracted_files
 
           EXTENSIONS="*.dll *.ini"
           [ "${{ github.event.inputs.extract_exe }}" == "true" ] && EXTENSIONS+=" *.exe"
 
           echo "Extracting files: $EXTENSIONS"
-          7z x "$ISO_FILE" -o"${{ github.workspace }}/download/extracted_files" -r -y $EXTENSIONS || { echo "Failed to extract files."; exit 1; }
+          7z x "$ISO_FILE" -o"download/extracted_files" -r -y $EXTENSIONS || { echo "Failed to extract files."; exit 1; }
 
           echo "Extracted files:"
-          find ${{ github.workspace }}/download/extracted_files -type f | while read -r file; do
+          find download/extracted_files -type f | while read -r file; do
             file_size_human=$(stat -c "%s" "$file")
             file_size_readable=$(numfmt --to=iec <<< "$file_size_human")
             echo "$file $file_size_readable ($file_size_human bytes)"
@@ -94,7 +94,7 @@ jobs:
 
       - name: Verify Extracted files
         run: |
-          find ${{ github.workspace }}/download/extracted_files -type f | while read -r file; do
+          find download/extracted_files -type f | while read -r file; do
               crc32_value=$(python3 -c "
           import zlib
           with open('$file', 'rb') as f:
