Update Extract_files_from_archive.yml

diff --git a/.github/workflows/Extract_files_from_archive.yml b/.github/workflows/Extract_files_from_archive.yml
--- a/.github/workflows/Extract_files_from_archive.yml
+++ b/.github/workflows/Extract_files_from_archive.yml
@@ -33,7 +33,7 @@ jobs:
 
       - name: Download Archive
         run: |
-          aria2c "${{ github.event.inputs.archive_url }}" -d ${{ github.workspace }}/download || { echo "Download failed"; exit 1; }
+          aria2c --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "${{ github.event.inputs.archive_url }}" -d ${{ github.workspace }}/download || { echo "Download failed"; exit 1; }
           echo "Downloaded archive files:"
           find ${{ github.workspace }}/download -type f | while read -r file; do
             file_size_human=$(stat -c "%s" "$file")
