Update Extract_files_from_archive.yml

diff --git a/.github/workflows/Extract_files_from_archive.yml b/.github/workflows/Extract_files_from_archive.yml
--- a/.github/workflows/Extract_files_from_archive.yml
+++ b/.github/workflows/Extract_files_from_archive.yml
@@ -26,7 +26,7 @@ jobs:
       - name: Install Dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y aria2 p7zip-full p7zip-rar python3 curl
+          sudo apt-get install -y aria2 p7zip-full p7zip-rar rar unrar python3 curl
 
       - name: Create Download Directory
         run: mkdir -p ${{ github.workspace }}/download
@@ -100,6 +100,12 @@ jobs:
               ;;
             tar.gz)
               tar -xzf "$ARCHIVE_FILE" --wildcards --no-anchored '*.dll' '*.ini' '*.exe' -C "${{ github.workspace }}/download/extracted_files" || { echo "Failed to extract files."; exit 1; }
+              ;;
+            rar)
+              unrar e "$ARCHIVE_FILE" "*.dll" "*.ini" "*.exe" "${{ github.workspace }}/download/extracted_files/" || { echo "Failed to extract files."; exit 1; }
+              ;;
+            7z)
+              7z x "$ARCHIVE_FILE" -o"${{ github.workspace }}/download/extracted_files" $EXTENSIONS || { echo "Failed to extract files."; exit 1; }
               ;;
             *)
               echo "Unsupported archive format."
